language: python
matrix:
  include:
    - stage: test
      python: 3.6
      env: TOXENV=isort,lint
    - stage: test
      python: 3.7
      env: TOXENV=isort,lint
      dist: xenial
      sudo: true
    - stage: deploy
      python: 3.6
      env: TOXENV=py36
    - stage: deploy
      python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install tox
# command to run tests
script:
  - tox
