language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
sudo: true
matrix:
  include:
    - python: 3.5
      env: TOXENV=isort
    - env: TONENV=lint 
    - python: 3.6
      env: TOXENV=isort
    - env: TONENV=lint 
    - python: 3.7
      env: TOXENV=isort
    - env: TONENV=lint 
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install tox
# command to run tests
script:
  - tox
  - make build-python-source
  - pip install dist/kimsufi-checker-0.1.0.tar.gz
