language: python
dist: xenial
matrix:
  include:
    - python: 3.5
      env: TOXENV=isort
    - env: TONENV=lint 
    - python: 3.6
      env: TOXENV=isort
    - env: TONENV=lint 
    - python: 3.7
      env: TOXENV=isort
    - env: TONENV=lint 
# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
  - tox
