language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=isort
    - python: 3.6
      env: TOXENV=isort
    - python: 3.7
      dist: xenial
      env: TOXENV=isort
    - python: 3.5
      env: TONENV=lint 
    - python: 3.6
      env: TONENV=lint 
    - python: 3.7
      dist: xenial
      env: TONENV=lint 
# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
  - tox
